/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppPageShell: typeof import('./../components/app-page-shell/app-page-shell.vue')['default']
    AppSection: typeof import('./../components/app-section/app-section.vue')['default']
  }
}
